### ISSUE TITLE
APIs 

### ISSUE THREAD

**Issue by itzmeowww** [programming-in-th/programming.in.th#664]
Please consider adding users APIs and problems APIs.

**Users APIs**

- Completed task
- ...

**Problems APIs**
- Number of all problems
- Number of solved/attempt/submission

**Comment by iammarkps** [comment]
will consider in next team meeting

**Comment by iammarkps** [comment]
This won't be done due to our API being tightly coupled to Next.JS, and generating a token for it would be too complex to be done for now.

However, we are planning on decoupling some of the API gradually, so I think it will be available with rate limit later this year or at the start of next year.

I will open a discussion after we ship v1.0.0
